function [FT1] = FTcalculation1(x,a,b,location)

[CrossArea_max,CrossArea_integration,CrossArea_mean,CrossArea_absmean,CrossArea_std,CrossArea_variation] ...
    = Fstatistics1(x.CrossArea(a:b),location(a:b));
[AreaChange_max,AreaChange_integration,AreaChange_mean,AreaChange_absmean,AreaChange_std,AreaChange_variation] ...
    = Fstatistics1(x.AreaChange(a:b),location(a:b));
[MajorAxis_max,MajorAxis_integration,MajorAxis_mean,MajorAxis_absmean,MajorAxis_std,MajorAxis_variation] ...
    = Fstatistics1(x.MajorAxis(a:b),location(a:b));
[MinorAxis_max,MinorAxis_integration,MinorAxis_mean,MinorAxis_absmean,MinorAxis_std,MinorAxis_variation] ...
    = Fstatistics1(x.MinorAxis(a:b),location(a:b));
[EquivDiameter_max,EquivDiameter_integration,EquivDiameter_mean,EquivDiameter_absmean,EquivDiameter_std,EquivDiameter_variation] ...
    = Fstatistics1(x.EquivDiameter(a:b),location(a:b));
[Eccentricity_max,Eccentricity_integration,Eccentricity_mean,Eccentricity_absmean,Eccentricity_std,Eccentricity_variation] ...
    = Fstatistics1(x.Eccentricity(a:b),location(a:b));
[Solidity_max,Solidity_integration,Solidity_mean,Solidity_absmean,Solidity_std,Solidity_variation] ...
    = Fstatistics1(x.Solidity(a:b),location(a:b));
[Extent_max,Extent_integration,Extent_mean,Extent_absmean,Extent_std,Extent_variation] ...
    = Fstatistics1(x.Extent(a:b),location(a:b));
[Curvature_max,Curvature_integration,Curvature_mean,Curvature_absmean,Curvature_std,Curvature_variation] ...
    = Fstatistics1(x.Curvature(a:b),location(a:b));
[Torsion_max,Torsion_integration,Torsion_mean,Torsion_absmean,Torsion_std,Torsion_variation] ...
    = Fstatistics1(x.Torsion(a:b),location(a:b));
FT1 = table(Curvature_max,Curvature_integration,Curvature_mean,Curvature_absmean,Curvature_std,Curvature_variation,...
    Torsion_max,Torsion_integration,Torsion_mean,Torsion_absmean,Torsion_std,Torsion_variation,...
    CrossArea_max,CrossArea_integration,CrossArea_mean,CrossArea_absmean,CrossArea_std,CrossArea_variation,...
    AreaChange_max,AreaChange_integration,AreaChange_mean,AreaChange_absmean,AreaChange_std,AreaChange_variation,...
    MajorAxis_max,MajorAxis_integration,MajorAxis_mean,MajorAxis_absmean,MajorAxis_std,MajorAxis_variation,...
    MinorAxis_max,MinorAxis_integration,MinorAxis_mean,MinorAxis_absmean,MinorAxis_std,MinorAxis_variation,...
    EquivDiameter_max,EquivDiameter_integration,EquivDiameter_mean,EquivDiameter_absmean,EquivDiameter_std,EquivDiameter_variation,...
    Eccentricity_max,Eccentricity_integration,Eccentricity_mean,Eccentricity_absmean,Eccentricity_std,Eccentricity_variation,...
    Solidity_max,Solidity_integration,Solidity_mean,Solidity_absmean,Solidity_std,Solidity_variation,...
    Extent_max,Extent_integration,Extent_mean,Extent_absmean,Extent_std,Extent_variation);
